name: Deploy to Sandbox
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global
      - name: Authenticate
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo $SFDX_AUTH_URL > auth.txt
          sfdx auth:sfdxurl:store -f auth.txt -a DevSandbox
      - name: Deploy to Sandbox
        run: sfdx force:source:deploy -p force-app -u DevSandbox --testlevel=RunLocalTests
